### ISSUE TITLE
xamber.tech is unavailable

### ISSUE THREAD

**Issue by keshamin** [Xamber/saturn#2]
I intended to check out a [demo page](https://xamber.tech), but the page doesn't load at all! 
Fix it, you lazy b*tch!

**Comment by Xamber** [comment]
@keshamin
The service has been stopped because of Covid-19.
The service was so cool and a lot of people were spending time with it without taking care of 2 kbytes rule.
So I decided to turn it off. 

(I don't use it much and 5$ Droplet seems expensive for nothing)
#returnthedemoback

**Comment by Xamber** [comment]
heh, I am going to test something and as a result - https://xamber.tech/ is available now =)
